version: '3'

services:
  node-service:
    image: node-service:1
    container_name: node-service-compose
    ports:
      - "3000:3000"
    networks:
      - BRIDGE
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-compose
    ports:
      - "27017:27017"
    networks:
      - BRIDGE
    restart: always
    volumes:
      - mongodb-data:/data/db

  dotnet-service:
    image: dotnet-service:1
    container_name: dotnet-service-compose
    ports:
      - "8080:8080"
    networks:
      - BRIDGE
    restart: always
    depends_on:
      - mongodb

networks:
  BRIDGE:
    driver: bridge

volumes:
  mongodb-data:
    external: true
    name: mongodb-data